### ISSUE TITLE
node-forge signed passes 

### ISSUE THREAD

**Issue by flomio** [destinationstransfers/passkit#11]
They don't seem to work ?

**Comment by tinovyatkin** [comment]
No, even if they pass `signpass` validation at test they don't work unfortunately. That's the reason why I rolled back NPM package and will rolling back changes to MASTER while investigating.

**Comment by scottire** [comment]
It seems the issue was an extra asn1 sequence element. 
Adding this fixes it.
```
 p7.sign();
 p7.contentInfo.value.pop();
```
Strange that `signpass` validation doesn't catch this error! 
credit: https://github.com/sublimator from @flomio

**Comment by sublimator** [comment]
Yeah, `signpass` and `openssl smime` both omit the actual signedData. They also use sha1 for the algorithm digest and not sha256, but it seems sha256 works.

**Comment by tinovyatkin** [comment]
@scottire @sublimator thank you! Removing extra `asn1` makes the trick! Released as `4.0.1` on NPM

**Comment by sublimator** [comment]
Nice!
