### ISSUE TITLE
Trailing slash in webServiceUrl

### ISSUE THREAD

**Issue by krivochenko** [destinationstransfers/passkit#127]
In process of render pass trailing slash added even if I specify webServiceUrl without it.
How I can control it? I need it because Wallet Union adds one more slash and requests `//v1/...` causes 404 error.

**Comment by tinovyatkin** [comment]
I can't reproduce it. Can you give the full URL you are setting to `webServiceURL`?

**Comment by krivochenko** [comment]
I set someting kind of `https://example.com`. In pass.json I see `https://example.com/`

**Comment by tinovyatkin** [comment]
Naked domain is not a valid URL for webservice....

**Comment by krivochenko** [comment]
What do you mean? What I have to set as a `webServiceUrl`?

**Comment by tinovyatkin** [comment]
I mean you don't have request path in such URL. So, from HTTPS point of view `https://example.com` and `https://example.com/` is the same, while latest is full URL. I understand that some application named Wallet Union doesn't know how to extend a path for an URL correctly, but doesn't see any error here on our side.
I'll let it be anyway in the next patch release.

**Comment by tinovyatkin** [comment]
Solved in [v6.4.9](https://github.com/destinationstransfers/passkit/releases/tag/v6.4.9)

**Comment by krivochenko** [comment]
Thanks!
