### ISSUE TITLE
Add property sharingProhibited

### ISSUE THREAD

**Issue by krivochenko** [destinationstransfers/passkit#142]
Hi
In some passes in pass.json I see `sharingProhibited: true`. This button hides "Share" button. 
Why it absent in your package?

**Comment by tinovyatkin** [comment]
That's interesting - this field in not in official documentation, but inside the Revision History. https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/RevisionHistory.html#//apple_ref/doc/uid/TP40012026-CH99-SW1

Do you want to make a PR?

**Comment by krivochenko** [comment]
https://github.com/destinationstransfers/passkit/pull/148

**Comment by PatrickQuintal** [comment]
@tinovyatkin 

I can certainly confirm that this is a _thing_. We use it.

I'll see if I'm able to convince my contact to update their documentation correctly. No promises~

**Comment by tinovyatkin** [comment]
Thank you @krivochenko, published as **[6.5.0](https://github.com/destinationstransfers/passkit/releases/tag/v6.5.0)**
