### ISSUE TITLE
Unexpected Indentifier

### ISSUE THREAD

**Issue by srbalan** [destinationstransfers/passkit#16]
![screen shot 2017-10-17 at 2 20 01 pm](https://user-images.githubusercontent.com/18670195/31649700-cb6314a2-b346-11e7-8d30-a7cdefde6d1a.png)

I am new with node.js, I don't understand what's wrong with my code. I just followed the instruction on your _readme_

**Comment by tinovyatkin** [comment]
You probably missed the first paragraph, regarding Node version requirement. You need to be on Node 8 to use `async` functions...

**Comment by srbalan** [comment]
Alright! Thanks :)
