### ISSUE TITLE
Error in template.js

### ISSUE THREAD

**Issue by srbalan** [destinationstransfers/passkit#17]
Please check line 32, 43, and 53. Remove the comma.
![screen shot 2017-10-17 at 2 58 49 pm](https://user-images.githubusercontent.com/18670195/31650852-db1c3af4-b34b-11e7-94d3-a7a08365e9d6.png)

**Comment by tinovyatkin** [comment]
Thank you for your report! This package is targeting Node 8 where this leading commas are perfectly fine.

**Comment by srbalan** [comment]
Alright! I am new in javascript. Thanks anyway :)
