### ISSUE TITLE
Missing Image Error

### ISSUE THREAD

**Issue by srbalan** [destinationstransfers/passkit#18]
![code](https://user-images.githubusercontent.com/18670195/31699580-3e7c7ea6-b3f6-11e7-8453-1eac046763cf.JPG)
![error](https://user-images.githubusercontent.com/18670195/31699585-4712b508-b3f6-11e7-9115-e593c7167e57.JPG)

**Comment by blowsie** [comment]
I also get this warning 
`(node:13752) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Missing image icon.png`

**Comment by tinovyatkin** [comment]
By Passkit specifications there is required images - `icon.png` always must be present in the pass. So, you must add it via `Template.load` or with something like `await template.images.loadFromDirectory("./images")`

**Comment by srbalan** [comment]
What's wrong with my code?

![code](https://user-images.githubusercontent.com/18670195/31875577-6592eb10-b801-11e7-85c8-b1d78455d32e.JPG)
![error](https://user-images.githubusercontent.com/18670195/31875582-6a45cb3c-b801-11e7-96ac-737dd85ce4ad.JPG)

**Comment by blowsie** [comment]
@srbalan you must use `await` inside an `async` function 

https://github.com/destinationstransfers/passkit/issues/3
