### ISSUE TITLE
Feature Request: Field Types

### ISSUE THREAD

**Issue by blowsie** [destinationstransfers/passkit#21]
This library strips out any meta information you add to a field using the `add` method.

This biggest downfall with this is you can't replicate the key value pairs found in the apple specification for;
- [Date Style Keys](https://developer.apple.com/library/content/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/FieldDictionary.html#//apple_ref/doc/uid/TP40012026-CH4-SW6)
- [Number Style Keys](https://developer.apple.com/library/content/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/FieldDictionary.html#//apple_ref/doc/uid/TP40012026-CH4-SW7)

--- 

### Example

```
  pass.auxiliaryFields.add({
          key: "claim_expiryDate",
          label: "Expires",
          value: moment(offer.claim.expiryDate),
          dateStyle: 'PKDateStyleMedium'
        });
```

**Comment by tinovyatkin** [comment]
Implemented in version 6.0 released today.
