### ISSUE TITLE
end event never fires when calling pipe method

### ISSUE THREAD

**Issue by bryanbartow** [destinationstransfers/passkit#36]
I'm running on Lambda with Node 8.10. When calling `pipe` into a write stream, the `end` event is never emitted (nor is the `error` event, for that matter). Although the file's `finish` method is emitted, the .pkpass file seems to be corrupt.  Here's my code:
```
const file = fs.createWriteStream("/tmp/mypass.pkpass");
pass.on("error", error => {
    console.error(error);
    process.exit(1);
})
pass.on("end", function() {
    console.log("ended");
})
pass.pipe(file);
```

Taking the file returned to the client and attempting to install it, the system gives me the following error:
```
Failed to add pass: 'file:///Users/bryanbartow/Downloads/mypass.pkpass' Error Domain=PKPassKitErrorDomain Code=1 "The pass cannot be read because it isn’t valid." UserInfo={NSLocalizedDescription=The pass cannot be read because it isn’t valid., NSUnderlyingError=0x61000005bba0 {Error Domain=PKPassKitErrorDomain Code=1 "(null)"}}.
```

Encoding the file as a base64 string, I can decode the string and end up with the contents of the zip(.pkpass) file. The proper files are all present. I just think this is an issue where the last few bytes aren't getting written to the zip file.  Has anyone else run into this?

Additionally, "downgrading" to `busbud/node-passbook` the `end` event fires on `pipe` and the resultant .pkpass file is recognized by the system.

**Comment by tinovyatkin** [comment]
Hi, thank you for report.
We have almost exact piece of code in `__test__`: https://github.com/destinationstransfers/passkit/blob/13f4c2051034d6a20d10f2b2d323c9aeaf07d384/__tests__/pass.js#L175

and it works well in test, but I'll take a closer look with Node 8.10

**Comment by tinovyatkin** [comment]
Try this:
```js
pass.stream().pipe(file);
```

**Comment by bryanbartow** [comment]
`stream().pipe()` seem to work.

**Comment by tinovyatkin** [comment]
We've decided to drop stream API since 6.0, offering new `async asBuffer()` method on `Pass`.
