### ISSUE TITLE
Does not support barcode?

### ISSUE THREAD

**Issue by Captnwalker1** [destinationstransfers/passkit#40]
I was following Apple's examples and the sign_pass utility successfully outputs the barcode object, but when using your passkit no barcode is on the pass

In my pass.json I have:
```
"barcode" : {
    "message" : "123456",
    "format" : "PKBarcodeFormatQR",
    "messageEncoding" : "iso-8859-1"
  },
```

But no barcode is present in the generated pass.

**Comment by Captnwalker1** [comment]
I found you can set the barcode programmatically. Wish it would pull from the json though

pass.barcodes([{
    message: "1234567890",
    format: 'PKBarcodeFormatQR',
    messageEncoding: 'iso-8859-1'
  }]);

**Comment by nickasd** [comment]
Thanks for your help. This should be mentioned in the README. Can somebody update it or is it ok I make a PR?

**Comment by tinovyatkin** [comment]
@nickasd We would love to see documentations PR - it's way needed and appreciated!

**Comment by nickasd** [comment]
Barcodes now seem to be accepted in the json, but I will make a PR for the readme to clarify other things.

**Comment by calpa** [comment]
```js
pass.barcodes = [{
    message: "1234567890",
    format: 'PKBarcodeFormatQR',
    messageEncoding: 'iso-8859-1'
 }];
``` 
 As the code changed to using setter.
