### ISSUE TITLE
end event not fired

### ISSUE THREAD

**Issue by nickasd** [destinationstransfers/passkit#43]
The `end` event is not fired, although the README says so:
```
const file = fs.createWriteStream("mypass.pkpass");
pass.on("end", () => {
  console.log('end');
})
pass.pipe(file);
```

**Comment by martinliptak** [comment]
I came across the same behavior. In my case, there was an error thrown in pass.pipe() which couldn't be handled because I didn't wait for the promise. Try doing

```
await pass.pipe(file);
```

or 

```
pass.pipe(file).catch(e => { throw e });
```

**Comment by nickasd** [comment]
Thanks for your help, but that didn't solve the problem since there is no error. Are you getting the `end` event?

**Comment by tinovyatkin** [comment]
We've dropped stream API at all since version 6.0

**Comment by nickasd** [comment]
What is the alternative then? In the section "Generate the file" of the README events are still mentioned.

**Comment by tinovyatkin** [comment]
@nickasd you probably looking for some outdated version, it's not mentioned in the README on `master`.
The only supported output now is a `Buffer`, like this:
```js
const buf = await pass.asBuffer()
```

**Comment by nickasd** [comment]
The README was apparently updated 9 hours later. Thanks!
