### ISSUE TITLE
Invalid certificate, no key found at decodePrivateKey 

### ISSUE THREAD

**Issue by asos-marcob** [destinationstransfers/passkit#44]
I keep getting this error when trying to generate the pass:

Error: Invalid certificate, no key found at decodePrivateKey (/...something.../passkit/node_modules/@destinationstransfers/passkit/src/lib/decodePrivateKey.js:14:11) at signManifest (/...something.../passkit/node_modules/@destinationstransfers/passkit/src/lib/signManifest-forge.js:31:15)

I have a pem file in the correct place, and the pem was generated by passkit-keys from a .p12 file exported from Keychain. I tried exporting a .p12 with the cert+private key, only the key or only the cert...to no avail, I always get the same problem.

Any hint?
Thanks!

**Comment by dsykesturner** [comment]
@asos-marcob have you encrypted the .p12 and .pem with a password? It's possible the private key isn't included in the .pem if you don't provide a password/pass phrase.

Also make sure you're providing the secret password to the template `template.keys("./keys", "secret");`

**Comment by asos-marcob** [comment]
yes, I gave it a password.

I load the keys with the following:
`template.keys("./keys", "pwd_here");`

But that shouldn't be a problem because the error happens before using the password.

`function decodePrivateKey(keydata, password, returnPEM = false) {
  const pemMessages = forge.pem.decode(keydata);

  // getting signer private key
  const signerKeyMessage = pemMessages.find(message =>
    message.type.includes('KEY'),
  );

  if (!signerKeyMessage) {
    throw new Error('Invalid certificate, no key found'); <======= fails here
  }

  const key = forge.pki.decryptRsaPrivateKey(
    forge.pem.encode(signerKeyMessage),
    password,
  );`

**Comment by asos-marcob** [comment]
That was it! Many thanks! Maybe worth adding it to the readme? ;)
