### ISSUE TITLE
Node 8.x support

### ISSUE THREAD

**Issue by c-bandy** [destinationstransfers/passkit#50]
As per #48 runtime support under node 10.1 was dropped. Node 8.x is still widely used as a runtime, especially in servers. I suggest that it should be supported a bit longer.

Also note that the [fs Promises API](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api) is still experimental in node 10.

These changes would be needed for node 8 support:
- `fs.promises` was unavailable prior to node 10.
  - Use a library like [normalize/mz](https://github.com/normalize/mz) for async fs operations, or use `Util.promisify` like before.
- [Don't use the global URL object](https://github.com/destinationstransfers/passkit/blob/master/src/template.js#L226). It was unavailable prior to node 10. 
   - `require('url').URL` references the same object in earlier versions.

**Comment by c-bandy** [comment]
As a more long-term solution targeting earlier versions of node with Babel during the build step could be a solution, which still means newer features can be used in the code without having to worry about compatibility.

**Comment by tinovyatkin** [comment]
The initial approach with this fork was to move on and use new Node features. We have older version published on NPM if you want to stick with an older version of Node. Version 6.0 released today is written in Typescript, but targeting Node 10.

**Comment by c-bandy** [comment]
Node 10 finally became available in [AWS Lambda](https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/) as of a few days ago, which was my pain point. So we will be able to move on for now.

With that said, I don't see the point of not targeting Node 8 when [it's still supported](https://github.com/nodejs/Release#release-schedule) and widely adopted. You guys should try to support current versions of node, like many other npm libraries.

PS. The 6.0.0 release is completely broken

**Comment by tinovyatkin** [comment]
@c-bandy Yes, 6.0 got NPM publishing error, will publish 6.1 with localizations support today.

**Comment by tinovyatkin** [comment]
@c-bandy version [6.1](https://github.com/destinationstransfers/passkit/releases/tag/v6.1.0) fixed NPM publishing issue
