### ISSUE TITLE
External signing of passes

### ISSUE THREAD

**Issue by timmy4all** [destinationstransfers/passkit#59]
The apple developer website best practices (and enterpise best practices) requries us to sign the passes on a separate system that handles private keys and signs files. 
Below reference from wallet developer guide
Best Practices
As you implement your web service, keep the following best practices in mind:
Always make a backup of your private key and certificate, and keep them in a secure place.
Avoid storing your private keys on your web server, because web servers typically have a larger attack surface. A more secure approach is to have a different server handle creating and signing passes, and push the finished passes to your web server.
https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Updating.html#//apple_ref/doc/uid/TP40012195-CH5-SW1

The template load function only allows to load certificates from a given location of keys,certs with password. Is it possible to externalize the signing like apple suggests?

**Comment by tinovyatkin** [comment]
Maybe my English is failing here, but it says `creating and signing passes` - that means complete pass creation (that what this library basically does). Since version 5.0 you can set certificate and private key with `.setCertificate` and string (i.e., env var for example).
I see no recommendation here to separate signing from creation process. It suggest you to separate whole process to another microservice may be...

**Comment by timmy4all** [comment]
Yes you are right. I see that the framework is using node-forge internally to sign the pass. Is it possible to inject the private key and certificate from a remote sftp? This way the certificates and keys dont have to reside on the application server and can stay within a  enterprise key and certificate mangement repository.

**Comment by tinovyatkin** [comment]
The feature to set private key and/or certificate from PEM encoded strings was added in the version 5.0. With earlier versions they must reside as files on filesystem.
