### ISSUE TITLE
Cannot add pass in wallet

### ISSUE THREAD

**Issue by dkladis** [destinationstransfers/passkit#80]
Hello, we have created a pass using your library, but we cannot add it to Apple Wallet.
We have tried to send it via email, download it from our server but iOS doesn't open Wallet.
Instead, it prompts us to select which application to use to open the pkpass file (Wallet is not in the list).

What could be the issue here??

**Comment by dkladis** [comment]
OK, we found that the relevantDate field was in an invalid format!

**Comment by tinovyatkin** [comment]
@dkladis  You can set `relevantDate` directly to Date object and the library will save it to correct format:
```js
pass.relevantDate = new Date(2019, 7, 7);
```
