### ISSUE TITLE
Support cyrillic text in pass.json

### ISSUE THREAD

**Issue by Asp3ctus** [destinationstransfers/passkit#83]
Hi
After updating from 4.3.1 to 6.4.0 the cyrillic text in pass.json became broken.

I have looked in to this issue and figured out that code in pass.ts
` 
   zip.push({ path: 'pass.json', data: JSON.stringify(this) });
`

should be
` 
    zip.push({ path: 'pass.json', data: Buffer.from(JSON.stringify(this)) });
`

So this way do-not-zip module will make correct files, otherwise it will make non english text to gibberish

I will make a pull request in a few.

**Comment by tinovyatkin** [comment]
Thank you @Asp3ctus! Do you want to make a PR?
I would recommend to use localizations for cyrillic text also. Or you are building Russian-only pass?

**Comment by Asp3ctus** [comment]
Yes russian only pass for now.
if you can make a fix without pull request then i'll be happy )

**Comment by Asp3ctus** [comment]
Okey, i'm on it)

**Comment by tinovyatkin** [comment]
Fixed in `6.4.4`, thank you!

**Comment by Asp3ctus** [comment]
Thanks, for lightning fast response and action!!!
This was awesome!!
